//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DO_AN_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCTK
    {
        public Nullable<int> Ban { get; set; }
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> Nhap { get; set; }
        public Nullable<int> Kho { get; set; }
        public Nullable<double> TongTien { get; set; }
    }
}
