//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DO_AN_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class InHoaDonXuat
    {
        public string MaSP { get; set; }
        public Nullable<int> Soluong { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public string MaKH { get; set; }
        public string HoTen { get; set; }
        public string SĐT { get; set; }
        public string MaHD { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string NguoiDung { get; set; }
        public string GhiChu { get; set; }
        public string TenSP { get; set; }
        public string TenNSX { get; set; }
        public string DiaChi { get; set; }
    }
}
