//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DO_AN_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class InPNH
    {
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public string MaPhieu { get; set; }
        public string MaSP { get; set; }
        public string TenNCC { get; set; }
        public string TenSP { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<double> SoLuongNhap { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
    }
}
